
// This file was auto-generated by ML.NET Model Builder. 

using MLModel1_ConsoleApp1;

class Program
{
    static void Main(string[] args)
    {
        // Create a list of sample data for model input
        List<MLModel1.ModelInput> samples = new List<MLModel1.ModelInput>()
        {
            new MLModel1.ModelInput() { Age = 18F, Sex = "male", Bmi = 33.77F, Children = 1F, Region = "southeast", },
            new MLModel1.ModelInput() { Age = 28F, Sex = "male", Bmi = 33.00F, Children = 3F, Region = "southeast", },
            new MLModel1.ModelInput() { Age = 33F, Sex = "male", Bmi = 22.705F, Children = 0F, Region = "northwest", },
            new MLModel1.ModelInput() { Age = 32F, Sex = "male", Bmi = 28.880F, Children = 0F, Region = "northwest", },
        };

        foreach (var sampleData in samples)
        {
            Console.WriteLine("Using model to make single prediction -- Comparing actual Charges with predicted Charges from sample data...\n\n");

            Console.WriteLine($"Age: {sampleData.Age}");
            Console.WriteLine($"Sex: {sampleData.Sex}");
            Console.WriteLine($"Bmi: {sampleData.Bmi}");
            Console.WriteLine($"Children: {sampleData.Children}");
            Console.WriteLine($"Region: {sampleData.Region}");
            // Assume "Charges" is a placeholder value as actual charges might not be available in this context
            Console.WriteLine($"Charges: {"Placeholder for actual charges if available"}");

            var predictionResult = MLModel1.Predict(sampleData);
            Console.WriteLine($"\n\nPredicted Charges: {predictionResult.Score}\n\n");

            Console.WriteLine("=============== Prediction Complete ===============\n");
        }

        Console.WriteLine("End of process, hit any key to finish.");
        Console.ReadKey();
    }
}
